import { ObjectType, Field } from "type-graphql";
import { Entity, Column } from "typeorm";

@ObjectType("Identifier")
export class IdentifierEntity{

    @Field({nullable: true, description: "The Card Kingdom card foil ID"})
    @Column({nullable: true})
    cardKingdomFoilId: string

    @Field({nullable: true, description: "The Card Kingdom card ID"})
    @Column({nullable: true})
    cardKingdomId: string

    @Field({nullable: true, description: "The Card Market card ID"})
    @Column({nullable: true})
    mcmId: string

    @Field({nullable: true, description: "The Card Market card meta ID"})
    @Column({nullable: true})
    mcmMetaId: string

    @Field({nullable: true, description: "The Magic: The Gathering Arena card ID"})
    @Column({nullable: true})
    mtgArenaId: string

    @Field({nullable: true, description: "The Magic: The Gathering Online card foil ID"})
    @Column({nullable: true})
    mtgoFoilId: string

    @Field({nullable: true, description: "The Magic: The Gathering Online card ID"})
    @Column({nullable: true})
    mtgoId: string

    @Field({ description: "A universal unique ID generated by MTGJSON. Each entry is unique. Entries are for MTGJSON v4 uuid generation"})
    @Column({nullable: true})
    mtgjsonV4Id: string

    @Field({nullable: true, description: "An string cards have which Wizards of the Coast uses as a card identifier"})
    @Column({nullable: true})
    multiverseId: string

    @Field({description: "A universal unique ID generated by Scryfall. Note that cards with multiple faces are not unique"})
    @Column({nullable: true})
    scryfallId: string

    @Field({nullable: true, description: "A unique ID for this card's oracle identity. This value is consistent across reprinted card editions, and unique among different cards with the same name (tokens, Unstable variants, etc)"})
    @Column({nullable: true})
    scryfallOracleId: string

    @Field({nullable: true, description: "A unique identifier for the card artwork that remains consistent across reprints. Newly spoiled cards may not have this field yet"})
    @Column({nullable: true})
    scryfallIllustrationId: string

    @Field({nullable: true, description: "The TCG Player card ID"})
    @Column({nullable: true})
    tcgplayerProductId: string

}